### ISSUE TITLE
Without the iFrame

### ISSUE THREAD

**Issue by Kastlebrick** [StackHive/DragDropInterface#3]
I like the concept of this, and have played around with it, however…

I would like to do something like this **without the iframe**, as I do not wish to work within an iFrame. But, I'm having a little trouble figuring out what needs to be altered in the dnd file to make this work.

**or, 'worst-case scenario' haha, target a div="content" in the frame (as apposed to the body).

Any chance an alternate/edited version of this can be provided.

**Comment by Kastlebrick** [comment]
Thanks for reopening this, but I have now figured out how to do this without the iframe..

**Comment by tayyab009** [comment]
can you provide me with the code of it without using iframe??
