### ISSUE TITLE
Eliminate the ability to drag into a tag

### ISSUE THREAD

**Issue by Kastlebrick** [StackHive/DragDropInterface#4]
How would I eliminate the ability to drag into a particular tag. This should be a default function, but it doesn't appear to be. See Screenshot:
![screenshot02005](https://cloud.githubusercontent.com/assets/19822533/18553995/5ad8672a-7b28-11e6-9949-49ce66e54063.jpg)

It should not be possible to drag a H1 tag (or any other elements) into a 'p' paragraph tag. The same thing is possible if there is a line break in the H1 tag.. you can drag other elements into it.

**Comment by kshitizshankar** [comment]
There are 2 things that you'll need to consider to implement that behaviour.
1. You'll have to control and list out which tag can go inside which ones. So here, for example, you'll have to defined that H1 cannot go inside H1
2. Run through this list of allowed tags in one of the drag events (DragEnter + DragLeave combination as DragOver gets fired too many times). Now this is where you can show a feedback to user for invalid drop zone.

OR 
You can just control this in the drop event and not show any feedback to user (I don't think that would work well from a UI/UX perspective).

P.S. I think I have a similar piece of code somewhere, will try to extend the existing code or add what I have here if possible. 
Hope this helps!

**Comment by Kastlebrick** [comment]
Not sure if this would be the 'best practice', but I ended up doing it in the OrchestrateDragDrop section. 

So, if the new element is being placed on/by the existing element it uses DecideBeforeAfter to decide the placement before or after the existing element.
