### ISSUE TITLE
No Elements dropping in Safari, on Windows

### ISSUE THREAD

**Issue by Kastlebrick** [StackHive/DragDropInterface#5]
Looks like there's an issue with no elements dropping into the page, in Safari, on Windows (10). ~found this on my demo, but the same thing happens on yours. 

The Drop Marker appears, console.log shows there is action, but no elements appear on the page when dropped.

**Comment by kshitizshankar** [comment]
I don't have a windows machine with me at the moment - it is working on my Mac - Safari (9.0.3).

**Comment by peter-dolkens** [comment]
Just some context on this.

Apple stopped supporting Safari 5 in May, 2012 - and subsequently pulled all support for Safari on Windows at that stage. It's almost impossible to find official download links to the final build (the files still exist on their CDN, but there's no official media pointing at them)

Personally, I'd suggest @Kastlebrick swap to a more recent browser. Windows 10 comes with Edge, though I prefer Chrome, which is extremely similar to Safari in my opinion.

**Comment by Kastlebrick** [comment]
As a dev, you should know it's important to do a cross browser check, on all major browsers, as well as test other devices to make sure that what you are building works across all platforms so that others using what you are building works for the user, regardless of the browser.  So, that's what this was. I personally use chrome. But not everyone does. 

After working with a website builder co., for 4+ years, I have come to realize that, for the most part, you can't tell someone to switch away from their favorite browser… As they will just switch away from using your service. Something to keep in mind. I mean, my God.. You know how many people are out there that are still using XP and Explorer, or Safari 6.1.6 on Mac OS X 10.7 ("Lion") or earlier. I get it, but not all users are willing to change. 

In the case of this ticket/issue, I decided to scrap the whole thing (the StackHive DragDrop Interface) and rebuild the concept from scratch, averting ondrop ( which is the issue with Windows/Safari ). What I have built now works in all browsers. So, thanks for the segue into DnD.

~

That being said ( not that you care to know ), once I figured out what the issue was, I decided to go try building a site with the stackhive.com editor, in Safari, to see if it was working there but I can't even get past the "Loading Code Editors ... " as it gets stuck at about 36 - 39%. It wont even load the editor in Safari. Not sure why.

**Comment by kshitizshankar** [comment]
@Kastlebrick Glad that you figured it out. As far as StackHive is concerned, it is a tool for developers/designers to create front-end and not for people who are using old browsers (Personally, I don't expect any developer using Explorer or Safari (Windows) to develop front-ends... I might be wrong!)

**Comment by Kastlebrick** [comment]
Yeah, you would be surprised how many do-it-yourselfers are out there,.. who are using uncommon setups. I know at some point you just have to tell them that it's not going to work, but at the same time try to a accommodate all scenarios(if possible). It's not like you can just build for one browser or OS, right. Expect the unexpected,, otherwise you are just shooting yourself in the foot. 

Look at it this way.. How many drag-and-drop website builders are out there? If it already exists, then why am I doing it myself? Same is true for someone who wants a website. There are plenty of developers out there who will build it for them, yet they don't want to do that.. And I can't blame them because I don't want to rely on a third party. While I do use a drag-and-drop builder, and they host some of my websites(currently),  I also have my own server/hosting & self hosted website(s) / services.
